### PR TITLE
DES-976 Updating java 8 version to 202 for kafka-connect-jdbc

### PR DESCRIPTION
**Pull request by ashilokhvostov**
Description of change
Updating CI Slave Java version 8 from 162 to 202

Motivation
Currently blocking PR builds to pass due to recent java version cleanup

### CODE REVIEW

**Comment by tradeshiftcicomponents** [comment]
Pushed docker image: `docker.tradeshift.net/tradeshift-kafka-connect-jdbc:ghprb-17fdee04b1b2fbf52c02282f082a0fc94880bd7f`

**Comment by ashilokhvostov** [comment]
retest

**Comment by tradeshiftcicomponents** [comment]
Pushed docker image: `docker.tradeshift.net/tradeshift-kafka-connect-jdbc:ghprb-17fdee04b1b2fbf52c02282f082a0fc94880bd7f`

**Comment by tradeshiftcicomponents** [comment]
Pushed docker image: `docker.tradeshift.net/tradeshift-kafka-connect-jdbc:ghprb-a814053424d07d97e204a32210f08488c2f33a8c`

**Pull request merged**
